import AuthContext from "./context/AuthContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthContext>
    <html lang="fr">
      <body>{children}</body>
    </html>
    </AuthContext>
  );
}
