import AuthContext from "./context/AuthContext";
import Header from "./components/Header"; // Adjust the path if necessary
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthContext>
      <html lang="fr">
        <body>
          <Header /> {/* Add the Header component here */}
          {children}
        </body>
      </html>
    </AuthContext>
  );
}

